version: '3.8'

services:
  # ---------------------------------------------
  #       SERVICIO DE BASE DE DATOS (SQL Server)
  # ---------------------------------------------
  db-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_db
    ports:
      - "1433:1433" # Puerto estándar de SQL Server
    environment:
      - ACCEPT_EULA=Y # Obligatorio para aceptar la licencia
      - MSSQL_SA_PASSWORD=yourStrong(!)Password # Cambia esto por un password seguro
      # (Opcional) Puedes crear la BBDD al inicio si quieres,
      # pero es más fácil hacerlo desde Spring o manualmente la primera vez.
    volumes:
      - mssql_data:/var/opt/mssql

  # ---------------------------------------------
  #        SERVICIO DE AUTENTICACIÓN (Keycloak)
  # ---------------------------------------------
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_server
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "9090:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  mssql_data:
  keycloak_data: