version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --http-port=8080 --import-realm
    volumes:
      - ./config/keycloak:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    networks:
      - viajes-network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Your_strong_Password1!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Q", "select 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - viajes-network

  viajes:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8004
      DB_HOST: db
      DB_PORT: 1433
      DB_NAME: tpi_logistica_db
      DB_USER: sa
      DB_PASS: "Your_strong_Password1!"
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/viajes-realm
    ports:
      - "8004:8004"
    depends_on:
      - db
      - keycloak
    networks:
      - viajes-network

volumes:
  mssql-data:

networks:
  viajes-network:
    driver: bridge

